name: Developer Setup
smtp:
  remote_server: smtp.qq.com:587
  host: localhost
  port: 8081
  user: 1262193323@qq.com
  pwd: kwjklcboqznsbabc
imap:
  network: tcp
  timeout: 10
  host: localhost
  port: 8080
  account:
    - remote_server: imap.qq.com:993
      auth:
        user: 1262193323@qq.com
        pwd: kwjklcboqznsbabc
      timeout: 0
      flush_time: 10
mongo:
  url: mongodb://127.0.0.1:27017
  db: mail_go
  grid_prefix: mail

